### ISSUE TITLE
Status Report 2 Feedback

### ISSUE THREAD

**Issue by kelly-phalen** [Qi-Li3/DS3500-Final-Project#6]

**Comment by samar14641** [comment]
Great work on report 2 @kelly-phalen @thexinyu @emily-ywang @Mtortolani @Qi-Li3!

Feedback:

- Data: It looks like you've got a data-collection pipeline working, so the next step is to make sure you've got all the data you need.

- Building the NLP model: This is going to be the most complicated part. The project proposal and report 1 had few candidate models, so you'll need to figure out which ones might work best for this project. Text data needs to be featurised before it can be used by the model. Featurising is essentially converting text into numeric features. 

This article (https://stackabuse.com/text-classification-with-python-and-scikit-learn/) has a fairly simple example on sentiment prediction using text data with NLTK and scikit-learn, and can be a good starting point for understanding featurising and a text-based ML pipeline.
